### PR TITLE
Additons in the home page. 

### PR DESCRIPTION
**Pull request by maxwellfundi**
@Patowhiz  here we are almost done. 

Quick things i need you to do for me. 

1. The image with the about us text on home page make it smaller man
2. The images on the 3 columns, center them
3. The tips component on homepage, could youmake that text a little bigger just like the on in other paragraphs. 

Then we would be completely done with home page, like done done.

### CODE REVIEW

**Comment by maxwellfundi** [comment]
@Patowhiz  the images for the news blurbs seems very squished. Could you have a look at the size we might need for a good appearance of the images?

**Comment by maxwellfundi** [comment]
@Patowhiz  the links on the news are very tiny, could you do somethign about that?

**Comment by Patowhiz** [comment]
@maxwellfundi this is now merged

**Comment by Patowhiz** [comment]
Pushing the above requested changes now.I've also noticed that the captions for the banner have not been added. Do you want me to make them invisible for now?

**Comment by maxwellfundi** [comment]
Yeh she has just said we remove them!

**Comment by Patowhiz** [comment]
Okay removing them now

**Comment by Patowhiz** [comment]
Done all of the above requested changes.

**Pull request merged**
